"""initial schema

Revision ID: 001
Revises: 
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('territorio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('nivel', sa.String(), nullable=False),
    sa.Column('padre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['padre_id'], ['territorio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_territorio_id'), 'territorio', ['id'], unique=False)
    
    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_producto_id'), 'producto', ['id'], unique=False)
    
    op.create_table('registrobalance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('año', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('territorio_id', sa.Integer(), nullable=False),
    sa.Column('mermas', sa.Float(), nullable=False),
    sa.Column('importacion', sa.Float(), nullable=False),
    sa.Column('disponible', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['territorio_id'], ['territorio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registrobalance_id'), 'registrobalance', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registrobalance_id'), table_name='registrobalance')
    op.drop_table('registrobalance')
    op.drop_index(op.f('ix_producto_id'), table_name='producto')
    op.drop_table('producto')
    op.drop_index(op.f('ix_territorio_id'), table_name='territorio')
    op.drop_table('territorio')
    # ### end Alembic commands ###
