"""add_fase2_tables

Revision ID: 5f5da875e5b7
Revises: aa879b17c78a
Create Date: 2026-07-13 14:13:47.734478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '5f5da875e5b7'
down_revision: Union[str, Sequence[str], None] = 'aa879b17c78a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poblacionhistorica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('año', sa.Integer(), nullable=False),
    sa.Column('territorio_id', sa.Integer(), nullable=False),
    sa.Column('poblacion_total', sa.Integer(), nullable=False),
    sa.Column('poblacion_urbana', sa.Integer(), nullable=False),
    sa.Column('poblacion_rural', sa.Integer(), nullable=False),
    sa.Column('hombres', sa.Integer(), nullable=False),
    sa.Column('mujeres', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['territorio_id'], ['territorio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nivel_acceso', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('territorio_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['territorio_id'], ['territorio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    op.create_index(op.f('ix_usuario_username'), 'usuario', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuario_username'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_table('poblacionhistorica')
    # ### end Alembic commands ###
