"""add_tipo_entidad_column

Revision ID: 71d1b324caa2
Revises: 5f5da875e5b7
Create Date: 2026-07-13 23:13:37.047145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '71d1b324caa2'
down_revision: Union[str, Sequence[str], None] = '5f5da875e5b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('territorio', sa.Column('tipo_entidad', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_territorio_nivel'), 'territorio', ['nivel'], unique=False)
    op.create_index(op.f('ix_territorio_nombre'), 'territorio', ['nombre'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_territorio_nombre'), table_name='territorio')
    op.drop_index(op.f('ix_territorio_nivel'), table_name='territorio')
    op.drop_column('territorio', 'tipo_entidad')
    # ### end Alembic commands ###
