"""add_consumo_per_capita_field

Revision ID: aa879b17c78a
Revises: 001
Create Date: 2026-07-12 12:11:09.929898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa879b17c78a'
down_revision: Union[str, Sequence[str], None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_producto_id', table_name='producto')
    # Agregar columna como nullable primero para datos existentes
    op.add_column('registrobalance', sa.Column('consumo_per_capita', sa.Float(), nullable=True))
    # Actualizar datos existentes con valor por defecto
    op.execute("UPDATE registrobalance SET consumo_per_capita = 0.0 WHERE consumo_per_capita IS NULL")
    # Luego cambiar a NOT NULL
    op.alter_column('registrobalance', 'consumo_per_capita', nullable=False)
    op.drop_index('ix_registrobalance_id', table_name='registrobalance')
    op.drop_index('ix_territorio_id', table_name='territorio')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_territorio_id', 'territorio', ['id'], unique=False)
    op.create_index('ix_registrobalance_id', 'registrobalance', ['id'], unique=False)
    op.drop_column('registrobalance', 'consumo_per_capita')
    op.create_index('ix_producto_id', 'producto', ['id'], unique=False)
    # ### end Alembic commands ###
